source:      .
destination: ./_site
plugins:     ./_plugins
lsi:      false
safe:     false
markdown: kramdown
pygments: true
permalink: pretty
paginate: 20

post_defaults:
  layout: post

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  use_coderay: false
